[build]
  publish = "docs"
  command = "DEBUG=* eleventy"

[[headers]]
  for = "/*"
  [headers.values]
  	Content-Security-Policy = "default-src 'unsafe-inline' 'self' sidecar.gitter.im gitter.im *.cryptocompare.com *.twitter.com *.twimg.com *.jquery.org data:"
  	X-Frame-Options = "SAMEORIGIN"
  	X-Content-Type-Options = "nosniff"
  	X-XSS-Protection = "1; mode=block"

[[plugins]]
package = "netlify-plugin-csp-generator"
  [plugins.inputs]
  buildDir = "docs"
  [plugins.inputs.policies]
    defaultSrc = "'self'"

[[redirects]]
  from = "/"
  to = "/en"
  status = 301